#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Izmir.Resource", IsApplication=true)]

namespace Izmir
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::Izmir.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::Izmir.Resource.String.Hello;
			global::SQLite.Resource.String.ApplicationName = global::Izmir.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Izmir.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Izmir.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Izmir.Resource.String.Hello;
			global::AutoMapper.Android.Resource.String.ApplicationName = global::Izmir.Resource.String.ApplicationName;
			global::AutoMapper.Android.Resource.String.Hello = global::Izmir.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int afcoi = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int afcoii = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int afcoiil = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int afcoil = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int afeti = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int afetii = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int afetiil = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int afetil = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int agri = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int agril = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int albert = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int aleksey = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int alex = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ali = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int alinda = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ammi = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int annab = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int annan = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ar = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ardab = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ardabe = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ardae = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int arrivals = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int barlas = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int berkay = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int c = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int cal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int can = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int chris = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int christina = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ciara = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int clim = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int climl = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int com = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int contact = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int cristina = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int cw1 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int cw2 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int cw3 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int david = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int denizs = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int departure = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int despina = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int deve = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int devel = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int dilge = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int dionysis = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int econi = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int econii = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int econiil = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int econil = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int egzon = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int egzon2 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int elisa = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int enescan = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ephesus = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int example1 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int example2 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int example3 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int example4 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int fatih = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int femm = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int femml = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int flora = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int furkan = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ga1 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ga2 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int gulsah = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int h = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int i = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int icon = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ilir = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int inta = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int intal = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ireme = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int iremg = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int isinsu = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int itre = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int itrel = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int izmir = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int jesper = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int julia = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int lea = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int libei = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int libeii = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int libeiii = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int libeiiil = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int libeiil = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int libeil = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int m = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int mathilde = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int megan = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int merel = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int mert = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int merte = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int noura = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int ogulcan = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int oliver = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int omer = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int oona = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int oscar = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int oyku = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int patrik = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int plus = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int post = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int pre = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int sebastian = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int selin = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int siebe = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int sofia = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int sophie = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int sophied = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int sponsors = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int storm = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int tb1 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int tb2 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int teos = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int turkish = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int undo = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int xaml = 2130837624;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
